
{{config (materialized='table')}}

WITH CUSTORDER AS 
(
SELECT C.CUSTOMERID AS CUST_ID, CONCAT(FIRSTNAME,'-',LASTNAME) AS FULL_NAME,
COUNT(ORDERID) AS ORDER_COUNT 
FROM L1_LANDING.CUSTOMERS C JOIN L1_LANDING.ORDERS O 
on C.CUSTOMERID=O.CUSTOMERID
GROUP BY CUST_ID ,FULL_NAME 
)
SELECT CUST_ID ,FULL_NAME,ORDER_COUNT FROM CUSTORDER ORDER BY ORDER_COUNT DESC