SELECT
O.ORDERID, O.ORDERDATE, O.CUSTOMERID, O.EMPLOYEEID, O.STOREID, O.STATUS_DESC, O.UPDATED_AT,
count(distinct O.ORDERID) as ORDER_COUNT,
sum((OI.QUANTITY * OI.UNITPRICE)) AS REVENUE
from 
{{ ref('order_stg') }} O
JOIN 
{{ ref('orderitem_stg')}} OI  ON O.ORDERID=OI.ORDERID
GROUP BY 
O.ORDERID, O.ORDERDATE, O.CUSTOMERID, O.EMPLOYEEID, O.STOREID, O.STATUS_DESC, O.UPDATED_AT